### ISSUE TITLE
2019.2.2已暴毙

### ISSUE THREAD

**Issue by qdyoungk** [luojunhui/touch-fish#1]

**Comment by luojunhui** [comment]
我机子上没有2.2的版本,无法重新问题,如果其他版本有问题无法使用,请尝试升级版本,如图所示版本:IntelliJ IDEA 2019.2.3 (Community Edition)
![image](https://user-images.githubusercontent.com/21333462/66629367-1a95f300-ec34-11e9-9102-185a1b7b1a16.png)

**Comment by qdyoungk** [comment]
你好，
我已更新2.3版本，仍然没有反应。不晓得是不是我配置问题吗？配置贴在下面了。谢谢回复嗷





配置页：

------------------ 原始邮件 ------------------
发件人: "junhui"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午2:35
收件人: "luojunhui/touch-fish"<touch-fish@noreply.github.com>;
抄送: "Xi"<1399312125@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [luojunhui/touch-fish] 2019.2.2已暴毙 (#1)




我机子上没有2.2的版本,无法重新问题,如果其他版本有问题无法使用,请尝试升级版本,如图所示版本:IntelliJ IDEA 2019.2.3 (Community Edition)

**Comment by luojunhui** [comment]
@yangkunqd 你的贴图没有成功,看不到你的配置

**Comment by qdyoungk** [comment]
可能是截图的问题，我保存后在发送试试。




------------------ 原始邮件 ------------------
发件人: "junhui"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午2:47
收件人: "luojunhui/touch-fish"<touch-fish@noreply.github.com>;
抄送: "Xi"<1399312125@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [luojunhui/touch-fish] 2019.2.2已暴毙 (#1)




@yangkunqd 你的贴图没有成功,看不到你的配置

**Comment by qdyoungk** [comment]
嗷  我是用邮件回的。。怪不得没图片
![配置](https://user-images.githubusercontent.com/42015391/66630517-099ab100-ec37-11e9-8b2a-4bccb620e6c5.png)
![状况及版本](https://user-images.githubusercontent.com/42015391/66630518-0a334780-ec37-11e9-959e-4e736d1f24d2.png)

**Comment by luojunhui** [comment]
1.  确保文件路径无误且内容不为空;
2.  第一步没问题后,保存settings后,重启IDEA.

**Comment by qdyoungk** [comment]
仍然为空，报错如下
![异常](https://user-images.githubusercontent.com/42015391/66631061-0c49d600-ec38-11e9-82fb-b14626298270.png)

**Comment by luojunhui** [comment]
你的JDK版本换成1.8以上试试?

**Comment by qdyoungk** [comment]
就是1.8的
![jdk](https://user-images.githubusercontent.com/42015391/66631716-6f883800-ec39-11e9-9414-63db81c7ea25.png)

**Comment by luojunhui** [comment]
@yangkunqd 刚用同事的windows上的IDEA测试了一下,确实会报错,请先暂停使用吧,等我修复下.

**Comment by qdyoungk** [comment]
好哒~

**Comment by luojunhui** [comment]
你好,因为最近换了工作,无法在之前的电脑上复现这个bug,但我在自己的win7 64位笔记本上系统上装了IDEA 2019.2.4,没有复现该问题,但我猜测是获取不到文件导致的,所以v2.3版本修改成 选择txt文件的方式替代之前的输入文件路径,可以尝试一波.

**Comment by luojunhui** [comment]
请更新最新版使用，如有问题，可以邮件联系我
