### ISSUE TITLE
2018.1 和2020.2

### ISSUE THREAD

**Issue by HGXG** [luojunhui/touch-fish#2]
jar文件是github最新的，macOS系统下的2018.1 和2020.2 idea 都找不到设置路径的
![image](https://user-images.githubusercontent.com/16718550/88890277-f9120080-d273-11ea-8773-edbbcff10c45.png)

**Comment by liushuliushu** [comment]
有个空指针小小bug，我fork了一下，等作者同意更改就好了

**Comment by luojunhui** [comment]
> jar文件是github最新的，macOS系统下的2018.1和2020.2 idea都找不到设置路径的
> ![图片](https://user-images.githubusercontent.com/16718550/88890277-f9120080-d273-11ea-8773-edbbcff10c45.png)
我没有mac机子测试呢。。不过听说win10好像也有这个问题，等我抽空改下

**Comment by luojunhui** [comment]
请更新最新版使用，如有问题，可以邮件联系我
