### ISSUE TITLE
没有设置的地方

### ISSUE THREAD

**Issue by chen195327** [luojunhui/touch-fish#3]
提示Select configuration element in the tree to edit its settings
![image](https://user-images.githubusercontent.com/42802384/89098493-c5250f80-d41a-11ea-826d-aa1df53a79d2.png)

mac 系统 
phpstorm version 2019.3.4

**Comment by liushuliushu** [comment]
有个空指针小小bug，我fork了一下。

**Comment by luojunhui** [comment]
请更新最新版使用，如有问题，可以邮件联系我
