### ISSUE TITLE
关注公众号？

### ISSUE THREAD

**Issue by signner** [luojunhui/touch-fish#8]
![image](https://user-images.githubusercontent.com/26163984/113684253-a12b7380-96f7-11eb-8acb-e413670ae7b8.png)
什么情况？摸个鱼都不能让我好好摸嘛？关注就关注嘛，为什么还搜不到这个公众号

**Comment by xiaolicheng** [comment]
啊？代码里有吗，没注意呢。

**Comment by luojunhui** [comment]
老哥搞错了吧，我这个都开源的，哪来的广告？最近出租屋网络不好都上不了github，五一回老家网络才可以~~

**Comment by luojunhui** [comment]
close
